### ISSUE TITLE
ffmpeg.dll missing

### ISSUE THREAD

**Issue by Cyarutchiii** [austinmp/multi-kill-clipper#6]
![image](https://github.com/austinmp/multi-kill-clipper/assets/61437490/2f3f8fef-90e6-441c-8de8-5a8ed1230e30)

**Comment by austinmp** [comment]
Hey @Cyarutchiii  thanks for the bug report. I converted the download to a zip file which has resolved the issue.

Just curious, how did you find out about this app? If you've got any other suggestions, critiques, feature requests, or bugs to reports please feel free to reach out!

**Comment by Cyarutchiii** [comment]
I frantically searched google for a way to automatically clip it because it's a bother to record it all manually multiple times :)
